### PR TITLE
Control dev

### PR DESCRIPTION
**Pull request by xxjunxx**
1. add control manager to enable simulation of selected objects
2. add semantic manger to load streaming level
3. add symbolic logger in knowrob manager to start and end logging

### CODE REVIEW

**Comment by andreihaidu** [comment]
@xxjunxx you have conflicts because I removed the messages to have them in a separate plugin

**Comment by xxjunxx** [comment]
I will update proto repo and make pull request later

**Comment by xxjunxx** [comment]
I am fixing the merge conflict in my branch and I will keep all your changes. Or you want to close the pull request, and I make a new one

**Comment by andreihaidu** [comment]
@xxjunxx there are still conflicts, I am not sure which to keep and which not, so it is better if you fix them and do another PR

**Comment by xxjunxx** [comment]
I fixed the conflicts. So I have only worked on files under Classes/Knowrob and Classes/Control. And I have the latest version of USemLog and just add my code on that when fixing the merge conflict

**Pull request merged**
